### PR TITLE
Fix peer dependency issue with react-dom

### LINKED ISSUE #7: Get rid of peer dependencies warnings
When users install the plugin to their site, they'll met with 10s of dependencies warnings for graphql.
We have to use Gatsby's own graphql (gatsby/graphql). I'm not sure how to fix this?

Here's the messages:
```
Dereks-MacBook-Pro-2:test-ts derek$ yarn add gatsby-plugin-ts
yarn add v1.16.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "gatsby-plugin-ts > graphql-toolkit > graphql-import@0.7.1" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
warning "gatsby-plugin-ts > @graphql-codegen/core@1.3.1" has unmet peer dependency "graphql@^0.8.0 || ^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
warning "gatsby-plugin-ts > graphql-toolkit@0.2.14" has unmet peer dependency "graphql@^0.8.0 || ^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
warning "gatsby-plugin-ts > @graphql-codegen/core > @graphql-codegen/plugin-helpers@1.3.1" has unmet peer dependency "graphql@^0.8.0 || ^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
warning "gatsby-plugin-ts > @graphql-codegen/typescript > @graphql-codegen/visitor-plugin-common@1.3.1" has unmet peer dependency "graphql@^0.8.0 || ^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
warning "gatsby-plugin-ts > graphql-toolkit > graphql-tools@4.0.4" has unmet peer dependency "graphql@^0.13.0 || ^14.0.0".
warning "gatsby-plugin-ts > @graphql-codegen/typescript > @graphql-codegen/visitor-plugin-common > graphql-tag@2.10.1" has unmet peer dependency "graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
warning "gatsby-plugin-ts > graphql-toolkit > graphql-tools > apollo-link@1.2.12" has unmet peer dependency "graphql@^0.11.3 || ^0.12.3 || ^0.13.0 || ^14.0.0".
warning "gatsby-plugin-ts > graphql-toolkit > graphql-tools > apollo-utilities@1.3.2" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
```

### PR DESCRIPTION
**Pull request by jeffslofish**
Closes #7

### CODE REVIEW

**Comment by d4rekanguok** [comment]
@jeffslofish Wow, that was fast! I literally opened that issue minutes ago, thank you very much for your attention.
I wonder if there were some misunderstand here, this is the peer dependencies messages (I will copy this to the issue):
```
Dereks-MacBook-Pro-2:test-ts derek$ yarn add gatsby-plugin-ts
yarn add v1.16.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "gatsby-plugin-ts > graphql-toolkit > graphql-import@0.7.1" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
warning "gatsby-plugin-ts > @graphql-codegen/core@1.3.1" has unmet peer dependency "graphql@^0.8.0 || ^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
warning "gatsby-plugin-ts > graphql-toolkit@0.2.14" has unmet peer dependency "graphql@^0.8.0 || ^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
warning "gatsby-plugin-ts > @graphql-codegen/core > @graphql-codegen/plugin-helpers@1.3.1" has unmet peer dependency "graphql@^0.8.0 || ^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
warning "gatsby-plugin-ts > @graphql-codegen/typescript > @graphql-codegen/visitor-plugin-common@1.3.1" has unmet peer dependency "graphql@^0.8.0 || ^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
warning "gatsby-plugin-ts > graphql-toolkit > graphql-tools@4.0.4" has unmet peer dependency "graphql@^0.13.0 || ^14.0.0".
warning "gatsby-plugin-ts > @graphql-codegen/typescript > @graphql-codegen/visitor-plugin-common > graphql-tag@2.10.1" has unmet peer dependency "graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
warning "gatsby-plugin-ts > graphql-toolkit > graphql-tools > apollo-link@1.2.12" has unmet peer dependency "graphql@^0.11.3 || ^0.12.3 || ^0.13.0 || ^14.0.0".
warning "gatsby-plugin-ts > graphql-toolkit > graphql-tools > apollo-utilities@1.3.2" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
```

As you see, `react-dom` is not part of the warning, this plugin actually doesn't touch React at all. The problem here is that I can't simply add `graphql` as a peer dependencies... I'll close this, please open a new one if you want another pass at this!

**Comment by jeffslofish** [comment]
Hehe, I was searching for recent issues to work on that were tagged "help wanted". 

Oh, I was getting a different unmet peer dependency issue for react-dom. I believe all you have to do is run `npm install graphql-import`and then commit the package.json file, then run `npm install` for good measure. Although I'm not sure why you were getting different messages than me...

**Comment by d4rekanguok** [comment]
@jeffslofish  Thank you for the tip! I'll give that a try. Did you try it in a Gatsby environment? The message I shared is what shown when users install the plugin to their site, instead of running `yarn / npm install` in the plugin itself.

**Comment by jeffslofish** [comment]
Oh, no...sorry, I didn't understand that is what you were doing.

**Comment by d4rekanguok** [comment]
No worries! Thank you again for your attention.

**Pull request closed without merging**
